---
- name: Install specific Redis version on RedHat
  ansible.builtin.dnf:
    name: "redis-{{ redis_version }}-1.el9_8"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Redis on Ubuntu
  ansible.builtin.apt:
    name: "{{ redis_packages[ansible_os_family][0] }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Configure Redis
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_config_paths[ansible_os_family] }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Redis

- name: Enable and start Redis
  ansible.builtin.service:
    name: "{{ redis_services[ansible_os_family] }}"
    state: started
    enabled: true
